#!/usr/bin/env ruby
require 'fileutils'
require 'open-uri'

git_bundles = [ 
  "git://github.com/hsteinhilber/vim-ruby-debugger.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/scrooloose/syntastic.git",
  "git://github.com/scrooloose/nerdcommenter.git",
  "git://github.com/timcharper/textile.vim.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-vividchalk.git",
  "git://github.com/tpope/vim-endwise.git",
  "git://github.com/altercation/vim-colors-solarized.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tsaleh/vim-supertab.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/corntrace/bufexplorer.git",
  "git://github.com/skammer/vim-css-color.git",
  "git://github.com/kchmck/vim-coffee-script.git",
  "git://github.com/cakebaker/scss-syntax.vim.git"
]

vim_org_scripts = [
  ["jquery",        "12107", "syntax"],
  ["blackboard",    "11225", "colors"]
]

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

puts "WARNING: Deleting all current bundles!"
FileUtils.rm_rf bundles_dir
FileUtils.mkdir_p bundles_dir
FileUtils.cd bundles_dir

puts "Cloning plugins from github.com"
git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

puts "Downloading plugins from vim.org"
vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
